// <auto-generated />
using System;
using Assecor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assecor.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20181125021627_AddedTablePerson")]
    partial class AddedTablePerson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assecor.Data.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("Assecor.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<int?>("ColorId");

                    b.Property<string>("Lastname");

                    b.Property<string>("Name");

                    b.Property<string>("Zipcode");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Assecor.Data.Entities.Person", b =>
                {
                    b.HasOne("Assecor.Data.Entities.Color", "Color")
                        .WithMany("Persons")
                        .HasForeignKey("ColorId");
                });
#pragma warning restore 612, 618
        }
    }
}
